ASN-Module-Header { iso(1) identified-organization(3) dod(6)
    internet(1) private(4) enterprise(1) uic(17218) fcb(1) modules(0) header(1) v3(3) 0 }
    DEFINITIONS AUTOMATIC TAGS ::= BEGIN

-- imports and exports
-- EXPORTS ALL;

IMPORTS CompanyCode, Data, Timestamp
 FROM ASN-Module-GeneralData { iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) uic(17218) fcb(1) modules(0) general(5) v1(1) 0 };

-- ##############################################################################################
-- # UIC barcode header - version 3.0.0
-- #
-- # Naming and encoding conventions
-- #   - A bar code which is only static (printed on a paper), and for which the security is in the system,
-- #      does not need any of these elements.
-- #   - A bar code which is only static, and includes its own security, needs:
-- #  	  level1Signature
-- #      level1KeyAlg and level1SigningAlg if the associated key does not make this evident
-- #   - A dynamic bar code including static and dynamic signatures needs the same elements as a static bar code, plus:
-- #	  level2PublicKey, and level2Signature
-- #      level2SigningAlg and level2keyAlg if not evident
-- #
-- # The maximum size of a barcode is, per the Aztec specification ISO 24778, limited to 1914 bytes.
-- ##############################################################################################

-- The basic entry point of the barcode
UICBarcodeHeader ::= SEQUENCE {
    format      OCTET STRING (SIZE(2)), -- always set to "U3",
    contents    Contents
}

Contents ::= SEQUENCE {
    level2Data      Level2Data,
    -- The signature is calculated over the PER unaligned encoding of level2Data
    level2Signature OCTET STRING OPTIONAL
}

Level2Data ::= SEQUENCE {
    level1Data      Level1Data,
    -- The signature is calculated over the PER unaligned encoding of level1Data
    level1Signature OCTET STRING        OPTIONAL,
    -- Dynamic Content Data goes here
    level2Data      SEQUENCE OF Data
}

Level1Data ::= SEQUENCE {
    -- provider of the level 1 signature
    securityProvider    CompanyCode,
    keyId               INTEGER (0..99999)  OPTIONAL,
    -- This field MUST contain at most one well-known UIC data type (e.g. FCBn)
    data                SEQUENCE SIZE(1..16) OF Data,

    -- object identifier of the key algorithms, e.g.:
    --   EC secp256r1   1.2.840.10045.3.1.7
    --   Ed25519        1.3.101.112 - no signing alg identifier required
    --   Ed448          1.3.101.113 - no signing alg identifier required
    --   DSA            1.2.840.10040.4.1 - not recommended for new deployments
    --   HMAC SHA256    1.2.840.113549.2.9 - no signing alg identifier required, not permitted except by bilateral agreement
    -- Not required to be set if the key ID makes it evident what key type was used.
    level1KeyAlg        OBJECT IDENTIFIER               OPTIONAL,
    level2KeyAlg        OBJECT IDENTIFIER               OPTIONAL,

    -- object identifier of the signing algorithm, e.g.:
    --   ECDSA with SHA256  1.2.840.10045.4.3.2
    --   DSA with SHA256    2.16.840.1.101.3.4.3.2 - not recommended for new deployments
    --   DSA with SHA224    2.16.840.1.101.3.4.3.1 - not recommended for new deployments
    --   DSA with SHA1      1.2.840.10040.4.3 - not recommended for new deployments
    level1SigningAlg    OBJECT IDENTIFIER               OPTIONAL,
    level2SigningAlg    OBJECT IDENTIFIER               OPTIONAL,

    -- This field SHALL be encoded as follows:
    --   For EC keys: the public key in the SEC 1 v2.0 compressed-point format
    --   For Ed25519/Ed448 keys: the raw 32/57-octet public key
    --   For DSA keys: the public key in the SubjectPublicKeyInfo format - not recommended due to size
    level2PublicKey     OCTET STRING                    OPTIONAL,

    -- End of the validity of the barcode.
    -- After this date and time the bar code needs to be regenerated by the provider of the ticket.
    -- The provider of the bar code should ensure that the endOfValidity given here does not exceed the validity of the key pair used on level 2.
    endOfValidity       Timestamp                       OPTIONAL,

    -- Validity duration in seconds of the barcode with reference to the time stamp in the dynamic content data
   	validityDuration    INTEGER (1..3600)               OPTIONAL,

   	...
}

END
