/*
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as
 *   published by the Free Software Foundation, either version 3 of
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 *
 */
package org.uic.ticket.api.asn.omv1;

import net.gcdc.asn1.datatypes.Asn1BigInteger;
import net.gcdc.asn1.datatypes.Asn1Optional;
import net.gcdc.asn1.datatypes.IntRange;
import net.gcdc.asn1.datatypes.Sequence;

@Sequence
public class SeriesDetailType extends Object {
	public SeriesDetailType() {
	}

	@IntRange(minValue=1,maxValue=32000)
	@Asn1Optional public Long supplyingCarrier;

	@IntRange(minValue=1,maxValue=99)
	@Asn1Optional public Long offerIdentification;

	@Asn1Optional public Asn1BigInteger series;
	

	public Long getSupplyingCarrier() {

		return this.supplyingCarrier;
	}

	public Long getOfferIdentification() {

		return this.offerIdentification;
	}

	public Long getSeries() {

		return Asn1BigInteger.toLong(this.series);
	}

	public void setSupplyingCarrier(Long supplyingCarrier) {

		this.supplyingCarrier = supplyingCarrier;
	}

	public void setOfferIdentification(Long offerIdentification) {

		this.offerIdentification = offerIdentification;
	}

	public void setSeries(Long series) {

		this.series = Asn1BigInteger.toAsn1(series);
	}

}
