/*
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as
 *   published by the Free Software Foundation, either version 3 of
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 *
 */
package org.uic.barcode.ticket.api.asn.omv2;

import org.uic.barcode.asn1.datatypes.Asn1Default;
import org.uic.barcode.asn1.datatypes.Asn1Optional;
import org.uic.barcode.asn1.datatypes.CharacterRestriction;
import org.uic.barcode.asn1.datatypes.FieldOrder;
import org.uic.barcode.asn1.datatypes.HasExtensionMarker;
import org.uic.barcode.asn1.datatypes.IntRange;
import org.uic.barcode.asn1.datatypes.RestrictedString;
import org.uic.barcode.asn1.datatypes.Sequence;


@Sequence
@HasExtensionMarker
public class CompartmentDetailsType extends Object {
	public CompartmentDetailsType() {
	}

	@FieldOrder(order = 0)
	@IntRange(minValue=1,maxValue=99)
	@Asn1Optional public Long coachType;

	@FieldOrder(order = 1)
	@IntRange(minValue=1,maxValue=99)
	@Asn1Optional public Long compartmentType;

	@FieldOrder(order = 2)
	@IntRange(minValue=1,maxValue=99)
	@Asn1Optional public Long specialAllocation;

	@FieldOrder(order = 3)
	@RestrictedString(CharacterRestriction.UTF8String)
	@Asn1Optional public String coachTypeDescr;

	@FieldOrder(order = 4)
	@RestrictedString(CharacterRestriction.UTF8String)
	@Asn1Optional public String compartmentTypeDescr;

	@FieldOrder(order = 5)
	@RestrictedString(CharacterRestriction.UTF8String)
	@Asn1Optional public String specialAllocationDescr;

	@FieldOrder(order = 6)
	@Asn1Default(value="unspecified")
	public CompartmentPositionType position;

	public Long getCoachType() {

		return this.coachType;
	}

	public Long getCompartmentType() {

		return this.compartmentType;
	}

	public Long getSpecialAllocation() {

		return this.specialAllocation;
	}

	public String getCoachTypeDescr() {

		return this.coachTypeDescr;
	}

	public String getCompartmentTypeDescr() {
	
		return this.compartmentTypeDescr;
	}

	public String getSpecialAllocationDescr() {

		return this.specialAllocationDescr;
	}

	public CompartmentPositionType getPosition() {
		if (position == null) return CompartmentPositionType.unspecified;
		return this.position;
	}

	public void setCoachType(Long coachType) {
		this.coachType = coachType;
	}

	public void setCompartmentType(Long compartmentType) {

		this.compartmentType = compartmentType;
	}

	public void setSpecialAllocation(Long specialAllocation) {

		this.specialAllocation = specialAllocation;
	}

	public void setCoachTypeDescr(String coachTypeDescr) {

		this.coachTypeDescr = coachTypeDescr;
	}

	public void setCompartmentTypeDescr(String compartmentTypeDescr) {

		this.compartmentTypeDescr = compartmentTypeDescr;
	}

	public void setSpecialAllocationDescr(String specialAllocationDescr) {

		this.specialAllocationDescr = specialAllocationDescr;
	}

	public void setPosition(CompartmentPositionType position) {

		this.position = position;
	}


}
