/*
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as
 *   published by the Free Software Foundation, either version 3 of
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 *
 */
package org.uic.barcode.ticket.api.asn.omv2;

import org.uic.barcode.asn1.datatypes.Asn1BigInteger;
import org.uic.barcode.asn1.datatypes.Asn1Default;
import org.uic.barcode.asn1.datatypes.Asn1Optional;
import org.uic.barcode.asn1.datatypes.CharacterRestriction;
import org.uic.barcode.asn1.datatypes.FieldOrder;
import org.uic.barcode.asn1.datatypes.HasExtensionMarker;
import org.uic.barcode.asn1.datatypes.IntRange;
import org.uic.barcode.asn1.datatypes.RestrictedString;
import org.uic.barcode.asn1.datatypes.Sequence;

@Sequence
@HasExtensionMarker
public class TariffType extends Object {
	public TariffType() {
	}
	@FieldOrder(order = 0)
	@IntRange(minValue=1,maxValue=200)
	@Asn1Default(value = "1")
	@Asn1Optional public Long numberOfPassengers;

	@FieldOrder(order = 1)
	@Asn1Optional public PassengerType passengerType;

	@FieldOrder(order = 2)
	@IntRange(minValue=1,maxValue=64)
	@Asn1Optional public Long ageBelow;

	@FieldOrder(order = 3)
	@IntRange(minValue=1,maxValue=128)
	@Asn1Optional public Long ageAbove;

	@FieldOrder(order = 5)
	@Asn1Optional public SequenceOfTravelerId traverlerid;

	@FieldOrder(order = 6)
	public Boolean restrictedToCountryOfResidence;

	@FieldOrder(order = 7)
	@Asn1Optional public RouteSectionType restrictedToRouteSection;

	@FieldOrder(order = 8)
	@Asn1Optional public SeriesDetailType seriesDataDetails;

	@FieldOrder(order = 9)
	@Asn1Optional public Asn1BigInteger tariffIdNum;

	@FieldOrder(order = 10)
	@RestrictedString(CharacterRestriction.IA5String)
	@Asn1Optional public String tariffIdIA5;

	@FieldOrder(order = 11)
	@RestrictedString(CharacterRestriction.UTF8String)
	@Asn1Optional public String tariffDesc;

	@FieldOrder(order = 12)
	@Asn1Optional public SequenceOfCardReferenceType reductionCard;
	


	public Long getNumberOfPassengers() {

		if (numberOfPassengers == null) {
			return new Long(1);
		}
		
		return this.numberOfPassengers;
	}

	public PassengerType getPassengerType() {

		return this.passengerType;
	}

	public Long getAgeBelow() {

		return this.ageBelow;
	}

	public Long getAgeAbove() {

		return this.ageAbove;
	}

	public SequenceOfTravelerId getTraverlerid() {

		return this.traverlerid;
	}

	public Boolean getRestrictedToCountryOfResidence() {

		return this.restrictedToCountryOfResidence;
	}

	public RouteSectionType getRestrictedToRouteSection() {

		return this.restrictedToRouteSection;
	}

	public SeriesDetailType getSeriesDataDetails() {

		return this.seriesDataDetails;
	}

	public Long getTariffIdNum() {

		return Asn1BigInteger.toLong(this.tariffIdNum);
	}

	public String getTariffIdIA5() {

		return this.tariffIdIA5;
	}

	public String getTariffDesc() {

		return this.tariffDesc;
	}

	public SequenceOfCardReferenceType getReductionCard() {

		return this.reductionCard;
	}

	public void setNumberOfPassengers(Long numberOfPassengers) {

		this.numberOfPassengers = numberOfPassengers;
	}

	public void setPassengerType(PassengerType passengerType) {

		this.passengerType = passengerType;
	}

	public void setAgeBelow(Long ageBelow) {

		this.ageBelow = ageBelow;
	}

	public void setAgeAbove(Long ageAbove) {

		this.ageAbove = ageAbove;
	}

	public void setTraverlerid(SequenceOfTravelerId traverlerid) {

		this.traverlerid = traverlerid;
	}

	public void setRestrictedToCountryOfResidence(Boolean restrictedToCountryOfResidence) {

		this.restrictedToCountryOfResidence = restrictedToCountryOfResidence;
	}

	public void setRestrictedToRouteSection(RouteSectionType restrictedToRouteSection) {

		this.restrictedToRouteSection = restrictedToRouteSection;
	}

	public void setSeriesDataDetails(SeriesDetailType seriesDataDetails) {

		this.seriesDataDetails = seriesDataDetails;
	}

	public void setTariffIdNum(Long tariffIdNum) {

		this.tariffIdNum = Asn1BigInteger.toAsn1(tariffIdNum);
	}

	public void setTariffIdIA5(String tariffIdIA5) {

		this.tariffIdIA5 = tariffIdIA5;
	}

	public void setTariffDesc(String tariffDesc) {

		this.tariffDesc = tariffDesc;
	}

	public void setReductionCard(SequenceOfCardReferenceType reductionCard) {

		this.reductionCard = reductionCard;
	}


}
