/*
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as
 *   published by the Free Software Foundation, either version 3 of
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 *
 */
package org.uic.barcode.ticket.api.asn.omv2;

import java.util.Collection;

import org.uic.barcode.asn1.datatypes.Asn1Optional;
import org.uic.barcode.asn1.datatypes.Asn1SequenceOf;
import org.uic.barcode.asn1.datatypes.FieldOrder;
import org.uic.barcode.asn1.datatypes.Sequence;

@Sequence
public class ValidityPeriodDetailType extends Object {
	public ValidityPeriodDetailType() {
	}

	@FieldOrder(order = 0)
	@Asn1Optional public SequenceOfValidityPeriodType validityPeriod;

	@FieldOrder(order = 1)
	@Asn1Optional public SequenceOfTimeRangeType excludedTimeRange;
	
	
	public class SequenceOfTimeRangeType extends Asn1SequenceOf<TimeRangeType> {
	    public SequenceOfTimeRangeType() { super(); }
	    public SequenceOfTimeRangeType(Collection<TimeRangeType> coll) { super(coll); }
	}		
	
	
	public class SequenceOfValidityPeriodType extends Asn1SequenceOf<ValidityPeriodType> {
	    public SequenceOfValidityPeriodType() { super(); }
	    public SequenceOfValidityPeriodType(Collection<ValidityPeriodType> coll) { super(coll); }
	}	

	public SequenceOfValidityPeriodType getValidityPeriod() {

		return this.validityPeriod;
	}

	public SequenceOfTimeRangeType getExcludedTimeRange() {

		return this.excludedTimeRange;
	}

	public void setValidityPeriod(SequenceOfValidityPeriodType validityPeriod) {

		this.validityPeriod = validityPeriod;
	}

	public void setExcludedTimeRange(SequenceOfTimeRangeType excludedTimeRange) {

		this.excludedTimeRange = excludedTimeRange;
	}


}
