/*
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as
 *   published by the Free Software Foundation, either version 3 of
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 *
 */
package org.uic.barcode.ticket.api.asn.omv1;

import java.math.BigInteger;

import org.uic.barcode.asn1.datatypes.Asn1BigInteger;
import org.uic.barcode.asn1.datatypes.Asn1Optional;
import org.uic.barcode.asn1.datatypes.CharacterRestriction;
import org.uic.barcode.asn1.datatypes.FieldOrder;
import org.uic.barcode.asn1.datatypes.HasExtensionMarker;
import org.uic.barcode.asn1.datatypes.RestrictedString;
import org.uic.barcode.asn1.datatypes.Sequence;


@Sequence
@HasExtensionMarker
public class CardReferenceType extends Object {
	public CardReferenceType() {
	}

	@FieldOrder(order = 0)
	@Asn1Optional public Asn1BigInteger cardIssuerNum;

	@FieldOrder(order = 1)
	@RestrictedString(CharacterRestriction.IA5String)
	@Asn1Optional public String cardIssuerIA5;

	@FieldOrder(order = 2)
	@Asn1Optional public Asn1BigInteger cardIdNum;

	@FieldOrder(order = 3)
	@RestrictedString(CharacterRestriction.IA5String)
	@Asn1Optional public String cardIdIA5;

	@FieldOrder(order = 4)
	@RestrictedString(CharacterRestriction.UTF8String)
	@Asn1Optional public String cardName;

	@FieldOrder(order = 5)
	@Asn1Optional public Asn1BigInteger cardType;

	@FieldOrder(order = 6)
	@Asn1Optional public Asn1BigInteger leadingCardIdNum;

	@FieldOrder(order = 7)
	@RestrictedString(CharacterRestriction.IA5String)
	@Asn1Optional public String leadingCardIdIA5;

	@FieldOrder(order = 8)
	@Asn1Optional public Asn1BigInteger trailingCardIdNum;

	@FieldOrder(order = 9)
	@RestrictedString(CharacterRestriction.IA5String)
	@Asn1Optional public String trailingCardIdIA5;
	

	public Asn1BigInteger getCardIssuerNum() {

		return this.cardIssuerNum;
	}

	public String getCardIssuerIA5() {

		return this.cardIssuerIA5;
	}

	public Asn1BigInteger getCardIdNum() {

		return this.cardIdNum;
	}

	public String getCardIdIA5() {

		return this.cardIdIA5;
	}

	public String getCardName() {

		return this.cardName;
	}

	public Asn1BigInteger getCardType() {
		return this.cardType;
	}

	public BigInteger getLeadingCardIdNum() {
		if (leadingCardIdNum != null) {
			return leadingCardIdNum.toBigInteger();
		}
		return null;
	}

	public String getLeadingCardIdIA5() {

		return this.leadingCardIdIA5;
	}

	public Long getTrailingCardIdNum() {

		return Asn1BigInteger.toLong(this.trailingCardIdNum);
	}

	public String getTrailingCardIdIA5() {

		return this.trailingCardIdIA5;
	}

	public void setCardIssuerNum(Long cardIssuerNum) {

		this.cardIssuerNum = Asn1BigInteger.toAsn1(cardIssuerNum);
	}

	public void setCardIssuerIA5(String cardIssuerIA5) {

		this.cardIssuerIA5 = cardIssuerIA5;
	}

	public void setCardIdNum(Asn1BigInteger asn1BigInteger) {

		this.cardIdNum = asn1BigInteger;
	}

	public void setCardIdNum(Long cardIdNum) {

		this.cardIdNum = new Asn1BigInteger(cardIdNum);
	}
	
	public void setCardIdIA5(String cardIdIA5) {

		this.cardIdIA5 = cardIdIA5;
	}

	public void setCardName(String cardName) {

		this.cardName = cardName;
	}

	public void setCardType(Long cardType) {

		this.cardType = Asn1BigInteger.toAsn1(cardType);
	}

	public void setLeadingCardIdNum(Long leadingCardIdNum) {

		this.leadingCardIdNum = Asn1BigInteger.toAsn1(leadingCardIdNum);
	}

	public void setLeadingCardIdIA5(String leadingCardIdIA5) {

		this.leadingCardIdIA5 = leadingCardIdIA5;
	}

	public void setTrailingCardIdNum(Long trailingCardIdNum) {

		this.trailingCardIdNum = Asn1BigInteger.toAsn1(trailingCardIdNum);
	}

	public void setTrailingCardIdIA5(String trailingCardIdIA5) {

		this.trailingCardIdIA5 = trailingCardIdIA5;
	}



}
