/*
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as
 *   published by the Free Software Foundation, either version 3 of
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 *
 */
package org.uic.barcode.ticket.api.asn.omv1;

import org.uic.barcode.asn1.datatypes.Choice;
import org.uic.barcode.asn1.datatypes.FieldOrder;
import org.uic.barcode.asn1.datatypes.HasExtensionMarker;


@Choice
@HasExtensionMarker
public class RegionalValidityType extends Object {
	public RegionalValidityType() {
	}

	@FieldOrder(order = 0)
	public TrainLinkType trainLink;

	@FieldOrder(order = 1)
	public ViaStationType viaStations;

	@FieldOrder(order = 2)
	public ZoneType zones;

	@FieldOrder(order = 3)
	public LineType lines;

	@FieldOrder(order = 4)
	public PolygoneType polygone;
	

	public TrainLinkType getTrainLink() {

		return this.trainLink;
	}

	public ViaStationType getViaStations() {

		return this.viaStations;
	}

	public ZoneType getZones() {

		return this.zones;
	}

	public LineType getLines() {

		return this.lines;
	}

	public PolygoneType getPolygone() {

		return this.polygone;
	}

	public void setTrainLink(TrainLinkType trainLink) {

		this.trainLink = trainLink;
	}

	public void setViaStations(ViaStationType viaStations) {

		this.viaStations = viaStations;
	}

	public void setZones(ZoneType zones) {

		this.zones = zones;
	}

	public void setLines(LineType lines) {

		this.lines = lines;
	}

	public void setPolygone(PolygoneType polygone) {

		this.polygone = polygone;
	}


}
