/*
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as
 *   published by the Free Software Foundation, either version 3 of
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 *
 */
package org.uic.barcode.ticket.api.asn.omv1;

import org.uic.barcode.asn1.datatypes.Asn1BigInteger;
import org.uic.barcode.asn1.datatypes.Asn1Default;
import org.uic.barcode.asn1.datatypes.Asn1Optional;
import org.uic.barcode.asn1.datatypes.CharacterRestriction;
import org.uic.barcode.asn1.datatypes.FieldOrder;
import org.uic.barcode.asn1.datatypes.HasExtensionMarker;
import org.uic.barcode.asn1.datatypes.IntRange;
import org.uic.barcode.asn1.datatypes.RestrictedString;
import org.uic.barcode.asn1.datatypes.Sequence;

@Sequence
@HasExtensionMarker
public class TicketLinkType extends Object {
	public TicketLinkType() {
	}

	@FieldOrder(order = 0)
	@RestrictedString(CharacterRestriction.IA5String)
	@Asn1Optional public String referenceIA5;

	@FieldOrder(order = 1)
	@Asn1Optional public Asn1BigInteger referenceNum;

	@FieldOrder(order = 2)
	@RestrictedString(CharacterRestriction.UTF8String)
	@Asn1Optional public String issuerName;
	
	@FieldOrder(order = 3)
	@RestrictedString(CharacterRestriction.IA5String)
	@Asn1Optional public String issuerPNR;	
	
	@FieldOrder(order = 4)
	@IntRange(minValue=1,maxValue=32000)
	@Asn1Optional public Long productOwnerNum;

	@FieldOrder(order = 5)
	@RestrictedString(CharacterRestriction.IA5String)
	@Asn1Optional public String productOwnerIA5;

	@FieldOrder(order = 6)
	@Asn1Default(value="openTicket")
	@Asn1Optional public TicketType ticketType;

	@FieldOrder(order = 7)
	@Asn1Default(value="issuedTogether")
	@Asn1Optional public LinkMode linkMode;

	public String getReferenceIA5() {

		return this.referenceIA5;
	}

	public Long getReferenceNum() {
		return Asn1BigInteger.toLong(this.referenceNum);
	}

	public String getIssuerName() {

		return this.issuerName;
	}

	public Long getProductOwnerNum() {

		return this.productOwnerNum;
	}

	public String getProductOwnerIA5() {

		return this.productOwnerIA5;
	}

	public TicketType getTicketType() {

		if (ticketType == null) {
			return TicketType.openTicket;
		}
		
		return this.ticketType;
	}

	public LinkMode getLinkMode() {

		if (linkMode == null){
			return LinkMode.issuedTogether;
		}
		
		return this.linkMode;
	}

	public void setReferenceIA5(String referenceIA5) {

		this.referenceIA5 = referenceIA5;
	}

	public void setReferenceNum(Long referenceNum) {
		this.referenceNum = Asn1BigInteger.toAsn1(referenceNum);
	}

	public void setIssuerName(String issuerName) {

		this.issuerName = issuerName;
	}

	public void setProductOwnerNum(Long productOwnerNum) {

		this.productOwnerNum = productOwnerNum;
	}

	public void setProductOwnerIA5(String productOwnerIA5) {

		this.productOwnerIA5 = productOwnerIA5;
	}

	public void setTicketType(TicketType ticketType) {

		this.ticketType = ticketType;
	}

	public void setLinkMode(LinkMode linkMode) {

		this.linkMode = linkMode;
	}

	public String getIssuerPNR() {
		return issuerPNR;
	}

	public void setIssuerPNR(String issuerPNR) {
		this.issuerPNR = issuerPNR;
	}
	
	


}
