/*
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as
 *   published by the Free Software Foundation, either version 3 of
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 *
 */
package org.uic.ticket.api.asn.omv2;

import net.gcdc.asn1.datatypes.Asn1BigInteger;
import net.gcdc.asn1.datatypes.Asn1Default;
import net.gcdc.asn1.datatypes.Asn1Optional;
import net.gcdc.asn1.datatypes.CharacterRestriction;
import net.gcdc.asn1.datatypes.HasExtensionMarker;
import net.gcdc.asn1.datatypes.IntRange;
import net.gcdc.asn1.datatypes.RestrictedString;
import net.gcdc.asn1.datatypes.Sequence;
import net.gcdc.asn1.datatypesimpl.SequenceOfStringIA5;

@Sequence
@HasExtensionMarker
public class ViaStationType extends Object {
	public ViaStationType() {
	}

	@Asn1Default("stationUIC")
	@Asn1Optional public CodeTableType stationCodeTable;

	@IntRange(minValue=1,maxValue=9999999)
	@Asn1Optional public Long stationNum;

	@RestrictedString(CharacterRestriction.IA5String)
	@Asn1Optional public String stationIA5;

	@Asn1Optional public SequenceOfViaStationType alternativeRoutes;

	@Asn1Optional public SequenceOfViaStationType route;

	@Asn1Optional public Boolean border = false;

	@Asn1Optional public SequenceOfCarrierNum carriersNum;

	@Asn1Optional public SequenceOfStringIA5 carriersIA5;

	@Asn1Optional public Asn1BigInteger seriesId;

	@Asn1Optional public Asn1BigInteger routeId;
	
	
	
	

	public CodeTableType getStationCodeTable() {

		if (stationCodeTable == null)  {
			return CodeTableType.stationUIC;
		}
		
		return this.stationCodeTable;
	}

	public Long getStationNum() {

		return this.stationNum;
	}

	public String getStationIA5() {

		return this.stationIA5;
	}

	public SequenceOfViaStationType getAlternativeRoutes() {

		return this.alternativeRoutes;
	}

	public SequenceOfViaStationType getRoute() {

		return this.route;
	}

	public Boolean getBorder() {

		return this.border;
	}

	public SequenceOfCarrierNum getCarriersNum() {

		return this.carriersNum;
	}

	public SequenceOfStringIA5 getCarriersIA5() {

		return this.carriersIA5;
	}

	public Long getSeriesId() {

		return Asn1BigInteger.toLong(this.seriesId);
	}

	public Long getRouteId() {

		return Asn1BigInteger.toLong(this.routeId);
	}

	public void setStationCodeTable(CodeTableType stationCodeTable) {

		this.stationCodeTable = stationCodeTable;
	}

	public void setStationNum(Long stationNum) {

		this.stationNum = stationNum;
	}

	public void setStationIA5(String stationIA5) {

		this.stationIA5 = stationIA5;
	}

	public void setAlternativeRoutes(SequenceOfViaStationType alternativeRoutes) {

		this.alternativeRoutes = alternativeRoutes;
	}

	public void setRoute(SequenceOfViaStationType route) {

		this.route = route;
	}

	public void setBorder(Boolean border) {

		this.border = border;
	}

	public void setCarriersNum(SequenceOfCarrierNum carriersNum) {

		this.carriersNum = carriersNum;
	}

	public void setCarriersIA5(SequenceOfStringIA5 carriersIA5) {

		this.carriersIA5 = carriersIA5;
	}

	public void setSeriesId(Long seriesId) {

		this.seriesId = Asn1BigInteger.toAsn1(seriesId);
	}

	public void setRouteId(Long routeId) {

		this.routeId = Asn1BigInteger.toAsn1(routeId);
	}


}
