/*
 *   This file was generated by openASN.1 - an open source ASN.1 toolkit for java
 *
 *   openASN.1 is Copyright (C) 2007 Clayton Hoss, Marc Weyland
 *
 *   openASN.1 is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as
 *   published by the Free Software Foundation, either version 3 of
 *   the License, or (at your option) any later version.
 *
 *   openASN.1 is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with openASN.1. If not, see <http://www.gnu.org/licenses/>.
 *
 */
package org.uic.ticket.api.asn.omv2;

import net.gcdc.asn1.datatypes.Asn1BigInteger;
import net.gcdc.asn1.datatypes.Asn1Default;

import net.gcdc.asn1.datatypes.Asn1Optional;
import net.gcdc.asn1.datatypes.CharacterRestriction;
import net.gcdc.asn1.datatypes.HasExtensionMarker;
import net.gcdc.asn1.datatypes.IntRange;
import net.gcdc.asn1.datatypes.RestrictedString;
import net.gcdc.asn1.datatypes.Sequence;
import net.gcdc.asn1.datatypesimpl.OctetString;
import net.gcdc.asn1.datatypesimpl.SequenceOfUnrestrictedLong;

@Sequence
@HasExtensionMarker

public class ZoneType extends Object {
	public ZoneType() {
	}

	@IntRange(minValue=1,maxValue=32000)
	@Asn1Optional public Long carrierNum;

	@RestrictedString(CharacterRestriction.IA5String)
	@Asn1Optional public String carrierIA5;

	@Asn1Default("stationUIC")
	@Asn1Optional public CodeTableType stationCodeTable;

	@IntRange(minValue=0,maxValue=9999999)
	@Asn1Optional public Long entryStationNum;

	@RestrictedString(CharacterRestriction.IA5String)
	@Asn1Optional public String entryStationIA5;

	@IntRange(minValue=0,maxValue=9999999)
	@Asn1Optional public Long terminatingStationNum;

	@RestrictedString(CharacterRestriction.IA5String)
	@Asn1Optional public String terminatingStationIA5;

	@Asn1Optional public Asn1BigInteger city;

	@Asn1Optional public SequenceOfUnrestrictedLong zoneId;

	@Asn1Optional public OctetString binaryZoneId;

	@Asn1Optional public String nutsCode;
	

	public Long getCarrierNum() {

		return this.carrierNum;
	}

	public String getCarrierIA5() {

		return this.carrierIA5;
	}

	public CodeTableType getStationCodeTable() {

		if (stationCodeTable == null)  {
			return CodeTableType.stationUIC;
		}
		
		return this.stationCodeTable;
	}

	public Long getEntryStationNum() {
		return this.entryStationNum;
	}

	public String getEntryStationIA5() {
		return this.entryStationIA5;
	}

	public Long getTerminatingStationNum() {
		return this.terminatingStationNum;
	}

	public String getTerminatingStationIA5() {
		return this.terminatingStationIA5;
	}

	public Asn1BigInteger getCity() {
		return this.city;
	}

	public SequenceOfUnrestrictedLong getZoneId() {
		return this.zoneId;
	}

	public byte[] getBinaryZoneId() {
		
		return binaryZoneId.toByteArray();
		
	}

	public String getNutsCode() {
		return this.nutsCode;
	}

	public void setCarrierNum(Long carrierNum) {
		this.carrierNum = carrierNum;
	}

	public void setCarrierIA5(String carrierIA5) {
		this.carrierIA5 = carrierIA5;
	}

	public void setStationCodeTable(CodeTableType stationCodeTable) {
		this.stationCodeTable = stationCodeTable;
	}

	public void setEntryStationNum(Long entryStationNum) {
		this.entryStationNum = entryStationNum;
	}

	public void setEntryStationIA5(String entryStationIA5) {
		this.entryStationIA5 = entryStationIA5;
	}

	public void setTerminatingStationNum(Long terminatingStationNum) {
		this.terminatingStationNum = terminatingStationNum;
	}

	public void setTerminatingStationIA5(String terminatingStationIA5) {
		this.terminatingStationIA5 = terminatingStationIA5;
	}

	public void setCity(Asn1BigInteger city) {
		this.city = city;
	}

	public void setZoneId(SequenceOfUnrestrictedLong zoneId) {
		this.zoneId = zoneId;
	}

	public void setBinaryZoneId(byte[] binaryZoneId) {
				
		this.binaryZoneId = new OctetString(binaryZoneId);

	}

	public void setNutsCode(String nutsCode) {
		this.nutsCode = nutsCode;
	}


}
